// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: internal/rpc/proto/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 传输无人机状态的请求
type DroneStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"` //无人机编号
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Position      *Position              `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Battery       *Battery               `protobuf:"bytes,6,opt,name=battery,proto3" json:"battery,omitempty"`
	Cpu           *CPUInfo               `protobuf:"bytes,7,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryInfo            `protobuf:"bytes,8,opt,name=memory,proto3" json:"memory,omitempty"`
	Network       *NetWorkInfo           `protobuf:"bytes,9,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneStatusRequest) Reset() {
	*x = DroneStatusRequest{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneStatusRequest) ProtoMessage() {}

func (x *DroneStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneStatusRequest.ProtoReflect.Descriptor instead.
func (*DroneStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *DroneStatusRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DroneStatusRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *DroneStatusRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DroneStatusRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *DroneStatusRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DroneStatusRequest) GetBattery() *Battery {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *DroneStatusRequest) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *DroneStatusRequest) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *DroneStatusRequest) GetNetwork() *NetWorkInfo {
	if x != nil {
		return x.Network
	}
	return nil
}

// 传输无人机状态的响应
type DroneStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneStatusResponse) Reset() {
	*x = DroneStatusResponse{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneStatusResponse) ProtoMessage() {}

func (x *DroneStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneStatusResponse.ProtoReflect.Descriptor instead.
func (*DroneStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *DroneStatusResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DroneStatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 位置信息
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// 电池状态
type Battery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      float32                `protobuf:"fixed32,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Battery) Reset() {
	*x = Battery{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Battery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Battery) ProtoMessage() {}

func (x *Battery) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Battery.ProtoReflect.Descriptor instead.
func (*Battery) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *Battery) GetCapacity() float32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// cpu状态
type CPUInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capacity        float32                `protobuf:"fixed32,1,opt,name=capacity,proto3" json:"capacity,omitempty"`                                      // 最大资源
	SurplusCapacity float32                `protobuf:"fixed32,2,opt,name=surplus_capacity,json=surplusCapacity,proto3" json:"surplus_capacity,omitempty"` // 剩余资源
	UsageRate       float32                `protobuf:"fixed32,3,opt,name=usage_rate,json=usageRate,proto3" json:"usage_rate,omitempty"`                   // 剩余资源
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *CPUInfo) GetCapacity() float32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CPUInfo) GetSurplusCapacity() float32 {
	if x != nil {
		return x.SurplusCapacity
	}
	return 0
}

func (x *CPUInfo) GetUsageRate() float32 {
	if x != nil {
		return x.UsageRate
	}
	return 0
}

// 内存内存
type MemoryInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capacity        float32                `protobuf:"fixed32,1,opt,name=capacity,proto3" json:"capacity,omitempty"`                                      // 最大资源
	SurplusCapacity float32                `protobuf:"fixed32,2,opt,name=surplus_capacity,json=surplusCapacity,proto3" json:"surplus_capacity,omitempty"` // 剩余资源
	UsageRate       float32                `protobuf:"fixed32,3,opt,name=usage_rate,json=usageRate,proto3" json:"usage_rate,omitempty"`                   // 使用率
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryInfo) GetCapacity() float32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *MemoryInfo) GetSurplusCapacity() float32 {
	if x != nil {
		return x.SurplusCapacity
	}
	return 0
}

func (x *MemoryInfo) GetUsageRate() float32 {
	if x != nil {
		return x.UsageRate
	}
	return 0
}

// 网络状态
type NetWorkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bandwidth     float32                `protobuf:"fixed32,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"` // 带宽Mbps
	Delay         float32                `protobuf:"fixed32,2,opt,name=delay,proto3" json:"delay,omitempty"`         // 延迟ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorkInfo) Reset() {
	*x = NetWorkInfo{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorkInfo) ProtoMessage() {}

func (x *NetWorkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorkInfo.ProtoReflect.Descriptor instead.
func (*NetWorkInfo) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{6}
}

func (x *NetWorkInfo) GetBandwidth() float32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *NetWorkInfo) GetDelay() float32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

type DroneSwarmChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    int32                  `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`        // 1: 添加无人机 2：删除无人机
	DroneUidList  []string               `protobuf:"bytes,2,rep,name=drone_uid_list,json=droneUidList,proto3" json:"drone_uid_list,omitempty"` // 变更的无人机的uid，添加时填入新无人机的uid，删除时填入要删除的无人机的uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneSwarmChangeRequest) Reset() {
	*x = DroneSwarmChangeRequest{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneSwarmChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneSwarmChangeRequest) ProtoMessage() {}

func (x *DroneSwarmChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneSwarmChangeRequest.ProtoReflect.Descriptor instead.
func (*DroneSwarmChangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{7}
}

func (x *DroneSwarmChangeRequest) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

func (x *DroneSwarmChangeRequest) GetDroneUidList() []string {
	if x != nil {
		return x.DroneUidList
	}
	return nil
}

type DroneSwarmChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneSwarmChangeResponse) Reset() {
	*x = DroneSwarmChangeResponse{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneSwarmChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneSwarmChangeResponse) ProtoMessage() {}

func (x *DroneSwarmChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneSwarmChangeResponse.ProtoReflect.Descriptor instead.
func (*DroneSwarmChangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{8}
}

func (x *DroneSwarmChangeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DroneSwarmChangeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DroneSwarmChangeResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DroneSwarmChangeResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

// 任务信息
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                          //任务ID
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                             //任务类型
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                                                    //任务优先级
	RequiredCpu    float32                `protobuf:"fixed32,4,opt,name=required_cpu,json=requiredCpu,proto3" json:"required_cpu,omitempty"`                                          // 任务执行所需的最低CPU
	RequiredMemory float32                `protobuf:"fixed32,5,opt,name=required_memory,json=requiredMemory,proto3" json:"required_memory,omitempty"`                                 // 任务执行所需的最低内存
	Cost           map[string]float32     `protobuf:"bytes,6,rep,name=cost,proto3" json:"cost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 资源消耗速率（每秒消耗电量）
	Target         *Position              `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`                                                                         // 目标位置（格式："x,y,z"）
	TaskParents    int32                  `protobuf:"varint,8,opt,name=task_parents,json=taskParents,proto3" json:"task_parents,omitempty"`
	TaskChildren   int32                  `protobuf:"varint,9,opt,name=task_children,json=taskChildren,proto3" json:"task_children,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` //任务状态
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{9}
}

func (x *Task) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetRequiredCpu() float32 {
	if x != nil {
		return x.RequiredCpu
	}
	return 0
}

func (x *Task) GetRequiredMemory() float32 {
	if x != nil {
		return x.RequiredMemory
	}
	return 0
}

func (x *Task) GetCost() map[string]float32 {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Task) GetTarget() *Position {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Task) GetTaskParents() int32 {
	if x != nil {
		return x.TaskParents
	}
	return 0
}

func (x *Task) GetTaskChildren() int32 {
	if x != nil {
		return x.TaskChildren
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 任务分配
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                           // 分配的任务 ID
	DroneId       string                 `protobuf:"bytes,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`                                                        // 分配的无人机 ID
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                                                    // 任务优先级
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                                                                         // 目标位置
	Cost          map[string]float32     `protobuf:"bytes,5,rep,name=cost,proto3" json:"cost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 资源消耗速率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *TaskAssignment) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskAssignment) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TaskAssignment) GetCost() map[string]float32 {
	if x != nil {
		return x.Cost
	}
	return nil
}

// 任务发送请求
type TasksSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksSendRequest) Reset() {
	*x = TasksSendRequest{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksSendRequest) ProtoMessage() {}

func (x *TasksSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksSendRequest.ProtoReflect.Descriptor instead.
func (*TasksSendRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{11}
}

func (x *TasksSendRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// 任务发送回复
type TasksSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksSendResponse) Reset() {
	*x = TasksSendResponse{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksSendResponse) ProtoMessage() {}

func (x *TasksSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksSendResponse.ProtoReflect.Descriptor instead.
func (*TasksSendResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{12}
}

func (x *TasksSendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 任务添加请求
type AddTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          bool                   `protobuf:"varint,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{13}
}

func (x *AddTaskRequest) GetTask() bool {
	if x != nil {
		return x.Task
	}
	return false
}

// 任务添加回复
type AddTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskResponse) Reset() {
	*x = AddTaskResponse{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskResponse) ProtoMessage() {}

func (x *AddTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskResponse.ProtoReflect.Descriptor instead.
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{14}
}

func (x *AddTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 任务分配结果
type TaskAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskAssignment      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignmentRequest) Reset() {
	*x = TaskAssignmentRequest{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignmentRequest) ProtoMessage() {}

func (x *TaskAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignmentRequest.ProtoReflect.Descriptor instead.
func (*TaskAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{15}
}

func (x *TaskAssignmentRequest) GetResults() []*TaskAssignment {
	if x != nil {
		return x.Results
	}
	return nil
}

// 确认任务分配结果
type TaskAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignmentResponse) Reset() {
	*x = TaskAssignmentResponse{}
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignmentResponse) ProtoMessage() {}

func (x *TaskAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_proto_simulation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignmentResponse.ProtoReflect.Descriptor instead.
func (*TaskAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_proto_simulation_proto_rawDescGZIP(), []int{16}
}

func (x *TaskAssignmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_rpc_proto_simulation_proto protoreflect.FileDescriptor

const file_internal_rpc_proto_simulation_proto_rawDesc = "" +
	"\n" +
	"#internal/rpc/proto/simulation.proto\x12\x06rpc.v1\"\xbf\x02\n" +
	"\x12DroneStatusRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12,\n" +
	"\bposition\x18\x05 \x01(\v2\x10.rpc.v1.PositionR\bposition\x12)\n" +
	"\abattery\x18\x06 \x01(\v2\x0f.rpc.v1.BatteryR\abattery\x12!\n" +
	"\x03cpu\x18\a \x01(\v2\x0f.rpc.v1.CPUInfoR\x03cpu\x12*\n" +
	"\x06memory\x18\b \x01(\v2\x12.rpc.v1.MemoryInfoR\x06memory\x12-\n" +
	"\anetwork\x18\t \x01(\v2\x13.rpc.v1.NetWorkInfoR\anetwork\";\n" +
	"\x13DroneStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"4\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"%\n" +
	"\aBattery\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x02R\bcapacity\"o\n" +
	"\aCPUInfo\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x02R\bcapacity\x12)\n" +
	"\x10surplus_capacity\x18\x02 \x01(\x02R\x0fsurplusCapacity\x12\x1d\n" +
	"\n" +
	"usage_rate\x18\x03 \x01(\x02R\tusageRate\"r\n" +
	"\n" +
	"MemoryInfo\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x02R\bcapacity\x12)\n" +
	"\x10surplus_capacity\x18\x02 \x01(\x02R\x0fsurplusCapacity\x12\x1d\n" +
	"\n" +
	"usage_rate\x18\x03 \x01(\x02R\tusageRate\"A\n" +
	"\vNetWorkInfo\x12\x1c\n" +
	"\tbandwidth\x18\x01 \x01(\x02R\tbandwidth\x12\x14\n" +
	"\x05delay\x18\x02 \x01(\x02R\x05delay\"`\n" +
	"\x17DroneSwarmChangeRequest\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\x05R\n" +
	"changeType\x12$\n" +
	"\x0edrone_uid_list\x18\x02 \x03(\tR\fdroneUidList\"n\n" +
	"\x18DroneSwarmChangeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\"\x8a\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\frequired_cpu\x18\x04 \x01(\x02R\vrequiredCpu\x12'\n" +
	"\x0frequired_memory\x18\x05 \x01(\x02R\x0erequiredMemory\x12*\n" +
	"\x04cost\x18\x06 \x03(\v2\x16.rpc.v1.Task.CostEntryR\x04cost\x12(\n" +
	"\x06target\x18\a \x01(\v2\x10.rpc.v1.PositionR\x06target\x12!\n" +
	"\ftask_parents\x18\b \x01(\x05R\vtaskParents\x12#\n" +
	"\rtask_children\x18\t \x01(\x05R\ftaskChildren\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x1a7\n" +
	"\tCostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xe7\x01\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\tR\adroneId\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x124\n" +
	"\x04cost\x18\x05 \x03(\v2 .rpc.v1.TaskAssignment.CostEntryR\x04cost\x1a7\n" +
	"\tCostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"6\n" +
	"\x10TasksSendRequest\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.rpc.v1.TaskR\x05tasks\"-\n" +
	"\x11TasksSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x0eAddTaskRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\bR\x04task\"+\n" +
	"\x0fAddTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x15TaskAssignmentRequest\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.rpc.v1.TaskAssignmentR\aresults\"2\n" +
	"\x16TaskAssignmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x81\x03\n" +
	"\x11SimulationService\x12F\n" +
	"\vDroneStatus\x12\x1a.rpc.v1.DroneStatusRequest\x1a\x1b.rpc.v1.DroneStatusResponse\x12U\n" +
	"\x10DroneSwarmChange\x12\x1f.rpc.v1.DroneSwarmChangeRequest\x1a .rpc.v1.DroneSwarmChangeResponse\x12@\n" +
	"\tTasksSend\x12\x18.rpc.v1.TasksSendRequest\x1a\x19.rpc.v1.TasksSendResponse\x12:\n" +
	"\aAddTask\x12\x16.rpc.v1.AddTaskRequest\x1a\x17.rpc.v1.AddTaskResponse\x12O\n" +
	"\x0eTaskAssignment\x12\x1d.rpc.v1.TaskAssignmentRequest\x1a\x1e.rpc.v1.TaskAssignmentResponseB\x0eZ\f./simulationb\x06proto3"

var (
	file_internal_rpc_proto_simulation_proto_rawDescOnce sync.Once
	file_internal_rpc_proto_simulation_proto_rawDescData []byte
)

func file_internal_rpc_proto_simulation_proto_rawDescGZIP() []byte {
	file_internal_rpc_proto_simulation_proto_rawDescOnce.Do(func() {
		file_internal_rpc_proto_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_simulation_proto_rawDesc), len(file_internal_rpc_proto_simulation_proto_rawDesc)))
	})
	return file_internal_rpc_proto_simulation_proto_rawDescData
}

var file_internal_rpc_proto_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_rpc_proto_simulation_proto_goTypes = []any{
	(*DroneStatusRequest)(nil),       // 0: rpc.v1.DroneStatusRequest
	(*DroneStatusResponse)(nil),      // 1: rpc.v1.DroneStatusResponse
	(*Position)(nil),                 // 2: rpc.v1.Position
	(*Battery)(nil),                  // 3: rpc.v1.Battery
	(*CPUInfo)(nil),                  // 4: rpc.v1.CPUInfo
	(*MemoryInfo)(nil),               // 5: rpc.v1.MemoryInfo
	(*NetWorkInfo)(nil),              // 6: rpc.v1.NetWorkInfo
	(*DroneSwarmChangeRequest)(nil),  // 7: rpc.v1.DroneSwarmChangeRequest
	(*DroneSwarmChangeResponse)(nil), // 8: rpc.v1.DroneSwarmChangeResponse
	(*Task)(nil),                     // 9: rpc.v1.Task
	(*TaskAssignment)(nil),           // 10: rpc.v1.TaskAssignment
	(*TasksSendRequest)(nil),         // 11: rpc.v1.TasksSendRequest
	(*TasksSendResponse)(nil),        // 12: rpc.v1.TasksSendResponse
	(*AddTaskRequest)(nil),           // 13: rpc.v1.AddTaskRequest
	(*AddTaskResponse)(nil),          // 14: rpc.v1.AddTaskResponse
	(*TaskAssignmentRequest)(nil),    // 15: rpc.v1.TaskAssignmentRequest
	(*TaskAssignmentResponse)(nil),   // 16: rpc.v1.TaskAssignmentResponse
	nil,                              // 17: rpc.v1.Task.CostEntry
	nil,                              // 18: rpc.v1.TaskAssignment.CostEntry
}
var file_internal_rpc_proto_simulation_proto_depIdxs = []int32{
	2,  // 0: rpc.v1.DroneStatusRequest.position:type_name -> rpc.v1.Position
	3,  // 1: rpc.v1.DroneStatusRequest.battery:type_name -> rpc.v1.Battery
	4,  // 2: rpc.v1.DroneStatusRequest.cpu:type_name -> rpc.v1.CPUInfo
	5,  // 3: rpc.v1.DroneStatusRequest.memory:type_name -> rpc.v1.MemoryInfo
	6,  // 4: rpc.v1.DroneStatusRequest.network:type_name -> rpc.v1.NetWorkInfo
	17, // 5: rpc.v1.Task.cost:type_name -> rpc.v1.Task.CostEntry
	2,  // 6: rpc.v1.Task.target:type_name -> rpc.v1.Position
	18, // 7: rpc.v1.TaskAssignment.cost:type_name -> rpc.v1.TaskAssignment.CostEntry
	9,  // 8: rpc.v1.TasksSendRequest.tasks:type_name -> rpc.v1.Task
	10, // 9: rpc.v1.TaskAssignmentRequest.results:type_name -> rpc.v1.TaskAssignment
	0,  // 10: rpc.v1.SimulationService.DroneStatus:input_type -> rpc.v1.DroneStatusRequest
	7,  // 11: rpc.v1.SimulationService.DroneSwarmChange:input_type -> rpc.v1.DroneSwarmChangeRequest
	11, // 12: rpc.v1.SimulationService.TasksSend:input_type -> rpc.v1.TasksSendRequest
	13, // 13: rpc.v1.SimulationService.AddTask:input_type -> rpc.v1.AddTaskRequest
	15, // 14: rpc.v1.SimulationService.TaskAssignment:input_type -> rpc.v1.TaskAssignmentRequest
	1,  // 15: rpc.v1.SimulationService.DroneStatus:output_type -> rpc.v1.DroneStatusResponse
	8,  // 16: rpc.v1.SimulationService.DroneSwarmChange:output_type -> rpc.v1.DroneSwarmChangeResponse
	12, // 17: rpc.v1.SimulationService.TasksSend:output_type -> rpc.v1.TasksSendResponse
	14, // 18: rpc.v1.SimulationService.AddTask:output_type -> rpc.v1.AddTaskResponse
	16, // 19: rpc.v1.SimulationService.TaskAssignment:output_type -> rpc.v1.TaskAssignmentResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_rpc_proto_simulation_proto_init() }
func file_internal_rpc_proto_simulation_proto_init() {
	if File_internal_rpc_proto_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_proto_simulation_proto_rawDesc), len(file_internal_rpc_proto_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_proto_simulation_proto_goTypes,
		DependencyIndexes: file_internal_rpc_proto_simulation_proto_depIdxs,
		MessageInfos:      file_internal_rpc_proto_simulation_proto_msgTypes,
	}.Build()
	File_internal_rpc_proto_simulation_proto = out.File
	file_internal_rpc_proto_simulation_proto_goTypes = nil
	file_internal_rpc_proto_simulation_proto_depIdxs = nil
}
